name: Deploy FastAPI to VMSS

on:
  push:
    branches: [ main ]

env:
  AZURE_RESOURCE_GROUP: demo
  AZURE_VMSS_NAME: pandu-ai
  PYTHON_VERSION: '3.10.12'
  AZURE_STORAGE_ACCOUNT: pandutoheed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create scripts container if not exists
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage container create --name scripts --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} --auth-mode login

    - name: Upload deployment scripts to Azure Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch -d scripts --account-name pandutoheed -s /Users/toheed/Projects/dummy/scripts --auth-mode login
          
    - name: Update VMSS model and trigger update
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az vmss extension set \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --vmss-name ${{ env.AZURE_VMSS_NAME }} \
            --name CustomScript \
            --publisher Microsoft.Azure.Extensions \
            --settings '{"fileUris":["https://${{ env.AZURE_STORAGE_ACCOUNT }}.blob.core.windows.net/scripts/deploy.sh"],"commandToExecute":"bash deploy.sh"}'
          
          az vmss update-instances --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_VMSS_NAME }} --instance-ids "*"

    - name: Azure logout
      run: |
        az logout
      if: always()